<?php

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 */
function kulturdesign_entity_browsers_form_alter(&$form, FormStateInterface &$form_state) {
	if (isset($form['#form_id'])) {
		if ($form['#form_id'] == 'entity_browser_kulturdesign_image_browser_form' ||
        $form['#form_id'] == 'entity_browser_kulturdesign_media_browser_form') {
// Attach our library.
			$form['#attached']['library'][] = 'kulturdesign_entity_browsers/view';
			$form['#attached']['library'][] = 'kulturdesign_entity_browsers/dropzone_css';

// Wrap actions so we can float them at the bottom of the browser.
			$form['actions_wrap'] = [
				'#type' => 'container',
				'#attributes' => [
					'class' => ['kulturdesign-entity-browser-actions'],
				],
			];

			if (isset($form['actions'])) {
				$form['actions_wrap'][] = $form['actions'];
				unset($form['actions']);
			}

			if (isset($form['widget']) && isset($form['widget']['actions'])) {
				$form['actions_wrap'][] = $form['widget']['actions'];
				unset($form['widget']['actions']);
			}

			if (!empty($form['selection_display'])) {
				$form['selection_display']['#weight'] = 100;
				$form['actions_wrap'][] = $form['selection_display'];
				unset($form['selection_display']);
			}

// Add a class for generic styling.
			$form['#attributes']['class'][] = 'kulturdesign-entity-browser-form';
		}
	}
}
